### ISSUE TITLE
Threads hanging

### ISSUE THREAD

**Issue by bryanshihpeng** [etheralm/libpurecool#1]
Hello,
I try to connect to my hp04,
and insert DYSON_PURE_HOT_COOL_DESK = "527" in consts.py
and edit is_dyson_pure_cool_device.

now hanging at line 168
self._state_data_available.get() in /libpurecool/dyson_pure_cool_link.py

please help

**Comment by etheralm** [comment]
Hi,
sorry about the late reply. It looks like the hp04 and I assume hd04 are the new hot+cool purifiers from 2018, sadly adding the device_id to consts won't be enough to add support for it. I don't have this model, but I think that with some assistance we can get it to work.
