### ISSUE TITLE
Unable to log into account

### ISSUE THREAD

**Issue by ajago** [etheralm/libpurecool#11]
Since approx Feb 3rd 3pm GMT I have been unable to log into my Dyson account.

I've added some print lines to `dyson.py` to get more info. When logging into Dyson the http request comes back with a status of 404 and a body of 

> {'Message': "No HTTP resource was found that matches the request URI 'https://api.cp.dyson.com/v1/userregistration/authenticate?country=US'."}

I've tried switching to a different network in order to test with a different IP, but get the same results. My script had been working for a couple of days before this, running every 10 minutes.
I've also verified that I can log into the Dyson app using the same credentials that my script uses.

**Comment by geekofweek** [comment]
See:
https://github.com/etheralm/libpurecool/pull/9

**Comment by ajago** [comment]
Didn't even think to check merged PRs. Cheers!
