### ISSUE TITLE
Proposal for testing

### ISSUE THREAD

**Issue by khzd** [etheralm/libpurecool#7]
hi etheralm

I have since some weeks a HP04 device and would like to manage it within HA.
I upload your dev lib and dev dyson component from respectively your git and HA dev branch. 
I'm not able to run them :(

How can I contribute ?
Cheers

**Comment by etheralm** [comment]
Hi,

thanks for the offer. I just posted instructions how to help with testing here: https://github.com/etheralm/libpurecool/issues/4

Let me know if you need any help with it.
